mode: paper
universe:
- TQQQ
- SOXL
bars:
  type: csv
  data_dir: data
  column: close
strategy:
  rsi_period: 14
  stoch_period: 14
  k_period: 3
  d_period: 3
  overbought: 80
  oversold: 20
  rsi_buy_threshold: 50
  rsi_buy_multiplier: 1.1
  enable_kd_buys: false
slices:
  total: 60
  per_entry_lt20: 2
  per_entry_20_80: 2
risk:
  equity: 80000
